{% set name = "python-rocksdb" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa692fbd06d8ed4ad641feee2970062fe01120e87b645a29403c71c628639e4f

build:
  number: 11
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - python
    - setuptools >=25
    - rocksdb 8
    - bzip2
    - cython >=0.20,<3
    - zlib
    - pip

  run:
    - python
    - setuptools >=25

test:
  imports:
    - rocksdb

about:
  home: https://github.com/twmht/python-rocksdb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python bindings for RocksDB'
  doc_url: https://python-rocksdb.readthedocs.io

extra:
  recipe-maintainers:
    - jeongseok-meta
    - maxibor
